version: '3.8'
services:
  postgres:
    image: postgres:14.4-alpine
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data

  postgres_test:
    image: postgres:14.4-alpine
    ports:
      - 5439:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_test
    restart: always
    volumes:
      - db_test:/var/lib/postgresql/data

volumes:
  db:
  db_test:
